--liquibase formatted sql

--changeset tubereturns:001
CREATE TABLE stocks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(10) NOT NULL UNIQUE,
    company_name  VARCHAR(500),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stocks_ticker_symbol ON stocks (ticker_symbol);

CREATE TABLE channels
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle                 VARCHAR(255) NOT NULL UNIQUE,
    channel_name           VARCHAR(500) NOT NULL,
    description            TEXT,
    thumbnail_data         BYTEA,
    thumbnail_content_type VARCHAR(50),
    last_processed_at      TIMESTAMP,
    deleted_at             TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_channels_handle ON channels (handle);

CREATE TABLE videos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id          VARCHAR(255) NOT NULL UNIQUE,
    channel_id        BIGINT       NOT NULL,
    title             TEXT         NOT NULL,
    published_at      TIMESTAMP    NOT NULL,
    duration_seconds  INTEGER,
    view_count        BIGINT,
    like_count        BIGINT,
    transcript_text   TEXT,
    transcript_status VARCHAR(50)  DEFAULT 'PENDING',
    processing_status VARCHAR(50)  DEFAULT 'PENDING',
    extraction_model  VARCHAR(100),
    excluded          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_videos_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE
);

CREATE INDEX idx_videos_video_id ON videos (video_id);
CREATE INDEX idx_videos_channel_id ON videos (channel_id);
CREATE INDEX idx_videos_published_at ON videos (published_at);
CREATE INDEX idx_videos_transcript_status ON videos (transcript_status);
CREATE INDEX idx_videos_processing_status ON videos (processing_status);

CREATE TABLE picks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id   BIGINT      NOT NULL,
    stock_id   BIGINT      NOT NULL,
    signal     VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_picks_video FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE,
    CONSTRAINT fk_picks_stock FOREIGN KEY (stock_id) REFERENCES stocks (id)
);

CREATE INDEX idx_picks_video_id ON picks (video_id);
CREATE INDEX idx_picks_stock_id ON picks (stock_id);
CREATE INDEX idx_picks_signal ON picks (signal);

CREATE TABLE stock_prices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id    BIGINT           NOT NULL,
    price_date  DATE             NOT NULL,
    close_price DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_prices_stock FOREIGN KEY (stock_id) REFERENCES stocks (id),
    CONSTRAINT uq_stock_prices_stock_date UNIQUE (stock_id, price_date)
);

CREATE INDEX idx_stock_prices_stock_id ON stock_prices (stock_id);
CREATE INDEX idx_stock_prices_price_date ON stock_prices (price_date);

CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('ADMIN'), ('FREE'), ('PRO');

CREATE TABLE users
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name                      VARCHAR(255) NOT NULL,
    email                           VARCHAR(255) NOT NULL UNIQUE,
    password_hash                   VARCHAR(255),
    provider                        VARCHAR(50)  NOT NULL DEFAULT 'local',
    provider_id                     VARCHAR(255),
    email_verified                  BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token              VARCHAR(255),
    verification_token_expires_at   TIMESTAMP,
    password_reset_token            VARCHAR(255),
    password_reset_token_expires_at TIMESTAMP,
    role_id                         BIGINT       NOT NULL REFERENCES roles(id),
    created_at                      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);

INSERT INTO users (first_name, email, password_hash, provider, email_verified, role_id, created_at, updated_at)
VALUES (
    'Balázs',
    'dbe128@gmail.com',
    '$2a$10$kTtjDcQpzW9XawfDcM3Io.v54X4lRBiimXEQntnzBz3RsmbQ3wroa',
    'local',
    TRUE,
    (SELECT id FROM roles WHERE name = 'ADMIN'),
    '2026-04-23 18:14:23.233111',
    '2026-04-23 18:14:45.451901'
);

--changeset tubereturns:002
ALTER TABLE videos ADD COLUMN exclusion_reason VARCHAR(255);

--changeset tubereturns:003 validCheckSum:ANY
CREATE TABLE channel_processing_notifications (
    id           BIGSERIAL PRIMARY KEY,
    channel_id   BIGINT NOT NULL REFERENCES channels(id),
    user_email   VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sent_at      TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_cpn_channel_id ON channel_processing_notifications(channel_id);
CREATE INDEX idx_cpn_sent_at ON channel_processing_notifications(sent_at);

--changeset tubereturns:004
ALTER TABLE channel_processing_notifications DROP COLUMN user_email;
ALTER TABLE channel_processing_notifications ADD COLUMN user_id BIGINT NOT NULL REFERENCES users(id);

--changeset tubereturns:005
ALTER TABLE channels ADD COLUMN subscriber_count BIGINT;

--changeset tubereturns:002-channel-discovery-complete
ALTER TABLE channels ADD COLUMN discovery_complete BOOLEAN NOT NULL DEFAULT FALSE;

--changeset tubereturns:003-seed-dev-user
INSERT INTO users (first_name, email, password_hash, provider, email_verified, role_id, created_at, updated_at)
VALUES (
    'Balázs2',
    'dbalazs128@gmail.com',
    '$2a$10$NRq54lV/dZ2jDp4I9/r82eLR5Ry4jYLCjXZrzd7GPslBQBZz080gi',
    'local',
    TRUE,
    (SELECT id FROM roles WHERE name = 'FREE'),
    '2026-05-12 09:13:30.579577',
    '2026-05-12 09:13:45.368842'
);

--changeset tubereturns:004-stock-unknown
ALTER TABLE stocks ADD COLUMN is_unknown BOOLEAN NOT NULL DEFAULT false;
