--liquibase formatted sql

--changeset tubereturns:001
--comment: Initial schema

CREATE TABLE stocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(10)  NOT NULL UNIQUE,
    company_name  VARCHAR(500),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stocks_ticker_symbol ON stocks(ticker_symbol);

CREATE TABLE channels (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_channel_id VARCHAR(255) NOT NULL UNIQUE,
    channel_name       VARCHAR(500) NOT NULL,
    description        TEXT,
    channel_url        VARCHAR(1000),
    last_processed_at  TIMESTAMP,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_channels_youtube_channel_id ON channels(youtube_channel_id);

CREATE TABLE videos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id          VARCHAR(255) NOT NULL UNIQUE,
    channel_id        BIGINT NOT NULL,
    title             TEXT NOT NULL,
    published_at      TIMESTAMP NOT NULL,
    duration_seconds  INTEGER,
    view_count        BIGINT,
    like_count        BIGINT,
    transcript_text   TEXT,
    transcript_status VARCHAR(50) DEFAULT 'PENDING',
    processing_status VARCHAR(50) DEFAULT 'PENDING',
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_videos_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE
);

CREATE INDEX idx_videos_video_id ON videos(video_id);
CREATE INDEX idx_videos_channel_id ON videos(channel_id);
CREATE INDEX idx_videos_published_at ON videos(published_at);
CREATE INDEX idx_videos_transcript_status ON videos(transcript_status);
CREATE INDEX idx_videos_processing_status ON videos(processing_status);

CREATE TABLE picks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id   BIGINT NOT NULL,
    stock_id   BIGINT NOT NULL,
    signal     VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_picks_video FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE,
    CONSTRAINT fk_picks_stock FOREIGN KEY (stock_id) REFERENCES stocks(id)
);

CREATE INDEX idx_picks_video_id ON picks(video_id);
CREATE INDEX idx_picks_stock_id ON picks(stock_id);
CREATE INDEX idx_picks_signal ON picks(signal);

CREATE TABLE stock_prices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id    BIGINT NOT NULL,
    price_date  DATE NOT NULL,
    close_price DOUBLE NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_prices_stock FOREIGN KEY (stock_id) REFERENCES stocks(id),
    CONSTRAINT uq_stock_prices_stock_date UNIQUE (stock_id, price_date)
);

CREATE INDEX idx_stock_prices_stock_id ON stock_prices(stock_id);
CREATE INDEX idx_stock_prices_price_date ON stock_prices(price_date);
