--liquibase formatted sql

--changeset tubereturns:002-users-schema
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('ADMIN'), ('FREE'), ('PRO');

CREATE TABLE users
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name                      VARCHAR(255) NOT NULL,
    email                           VARCHAR(255) NOT NULL UNIQUE,
    password_hash                   VARCHAR(255),
    provider                        VARCHAR(50)  NOT NULL DEFAULT 'local',
    provider_id                     VARCHAR(255),
    email_verified                  BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token              VARCHAR(255),
    verification_token_expires_at   TIMESTAMP,
    password_reset_token            VARCHAR(255),
    password_reset_token_expires_at TIMESTAMP,
    role_id                         BIGINT       NOT NULL REFERENCES roles(id),
    created_at                      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users (email);
