--liquibase formatted sql

--changeset tubereturns:006-exchange-rates
CREATE TABLE currencies (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL UNIQUE
);

CREATE TABLE exchange_rates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_id BIGINT           NOT NULL REFERENCES currencies(id),
    rate_date   DATE             NOT NULL,
    rate_to_usd DOUBLE PRECISION NOT NULL,
    CONSTRAINT uq_exchange_rates_currency_date UNIQUE (currency_id, rate_date)
);

CREATE INDEX idx_exchange_rates_currency_id ON exchange_rates(currency_id);
CREATE INDEX idx_exchange_rates_rate_date ON exchange_rates(rate_date);
